services:
  postgres:
    image: postgres:16-alpine
    container_name: auth_server_postgres_dev
    environment:
      POSTGRES_DB: auth_server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: auth_server_redis_dev
    command: redis-server --appendonly yes --requirepass redispassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auth_server_app_dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/auth_server
      REDIS_URL: redis://:redispassword@redis:6379
      JWT_ACCESS_SECRET: dev-access-secret-at-least-32-characters-long
      JWT_REFRESH_SECRET: dev-refresh-secret-at-least-32-characters-long
      JWT_ACCESS_EXPIRES_IN: "12h"
      JWT_REFRESH_EXPIRES_IN: "7d"
      SESSION_SECRET: dev-session-secret-at-least-32-characters-long
      CORS_ORIGIN: "http://localhost:3000,http://localhost:5173"
      CLIENT_URL: "http://localhost:5173"
      SERVER_URL: "http://localhost:3000"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./.env:/app/.env
      - ./logs:/app/logs
      - /app/node_modules  # Prevent overwriting node_modules
    restart: unless-stopped

volumes:
  postgres_data_dev:
  redis_data_dev: